### PR TITLE
NumPy 1.25 compatibility fixes

### PR DESCRIPTION
**Pull request by MeggyCal**
NumPy dropped nose support in https://github.com/numpy/numpy/pull/23041. Those two patches remove the problematic code and make the package tests NumPy 1.25 compatible. One of those patches was originally created by @s-t-e-v-e-n-k, the other by me. Those are just rough fixes, you may want to refine the changes before the next release.

### CODE REVIEW

**Comment by rc** [comment]
Thank you!

`README.rst` now needs to be updated, as `nosetests -v scikits.umfpack` no longer works. What is the correct command now?

**Comment by rc** [comment]
I can run the tests using `pytest scikits/umfpack/` from within the sources directory after it is installed, but not from outside the source directory as the README file states - am I right?

**Comment by s-t-e-v-e-n-k** [comment]
You have a few options here, you can use `pyproject.toml` or `pytest.ini` to tell pytest where your tests are, and then run pytest from the source directory. But not outside it, no.

**Comment by s-t-e-v-e-n-k** [comment]
The other option is `pytest <test directory>`, sorry hit Comment too fast :-)

**Comment by rc** [comment]
OK, I will update the README and push it here.

**Comment by rc** [comment]
Actually I have pushed my commit to https://github.com/rc/scikit-umfpack-rc/tree/no-more-nose, as I do not want to push to @MeggyCal's master branch.

**Comment by chemiskyy** [comment]
This would be great to merge since Numpy 1.25 and numpy 1.26 are become very popular. Is there anything I can do to help?I have unsuccessfully tried to open a PR on your branch @rc.

It is rather critical since scipy users are not aware of the non-use of scikit-umfpack, since it is correctly installed but not correctly imported, making this obscure to the end user

Thanks
Yves

**Comment by rc** [comment]
I was reluctant to push my commit to @MeggyCal's master branch, so this got stalled. Given the demand, I will merge my version then.

**Pull request merged**
