### PR TITLE
BUG: type Suitesparse_long to be UF_long.

### PR DESCRIPTION
**Pull request by xoviat**
This fixes the manylinux problems on 64 bit manylinux. There are still problems with 32 bit manylinux, but those are related to Python code that I did not write.

### CODE REVIEW

**Comment by xoviat** [comment]
Build matrices:
https://travis-ci.org/scikit-umfpack/scikit-umfpack-wheels/builds/288385238
https://ci.appveyor.com/project/rc/scikit-umfpack-wheels/build/1.0.34

**Comment by rc** [comment]
Thanks! Note that https://github.com/scipy/scipy/pull/7939 is needed with the current scikit-umfpack. Maybe the remaining errors are related?

**Comment by rc** [comment]
What is the size of `np.intc` on the failing platforms?

**Comment by xoviat** [comment]
Would that be `sys.getsizeof(np.intc)`?

**Comment by xoviat** [comment]
Update: this PR should fix everything *if* scipy 1.0 is installed (which it will be).

**Comment by rc** [comment]
Thanks! As for the size of `np.intc`, I just meant printing it:
```
In [5]: np.intc
Out[5]: numpy.int32
```

**Comment by xoviat** [comment]
I think this is ready to merge (though you should remove the explcit `scipy==1.0.0rc1` once scipy comes out.

**Comment by rc** [comment]
Yes, thank you, merging.

**Pull request merged**
