### PR TITLE
Version 0.3.1

### LINKED ISSUE #36: Many test errors of scikits.umfpack 0.3.0 on win-amd64
The 32-bit builds are OK. The 64-bit builds fail most tests:
```
Running unit tests for scikits.umfpack
NumPy version 1.13.1
NumPy relaxed strides checking option: True
NumPy is installed in X:\Python36\lib\site-packages\numpy
Python version 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
EEEEE.EEEX:\Python36\lib\importlib\_bootstrap.py:205: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
E.E.EE.EEEEE
======================================================================
ERROR: test_interface.TestSolvers.test_solve_complex_int64_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 56, in test_solve_complex_int64_umfpack
    x = um.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 56, in spsolve
    x = UmfpackLU(A).solve(b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 192, in __init__
    self.umf = UmfpackContext(family[A.dtype.char + A.indices.dtype.char])
KeyError: 'Dq'

======================================================================
ERROR: test_interface.TestSolvers.test_solve_complex_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 48, in test_solve_complex_umfpack
    x = um.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 56, in spsolve
    x = UmfpackLU(A).solve(b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 193, in __init__
    self.umf.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_zl_symbolic at 0x00000244E656E0D0> failed with UMFPACK_ERROR_out_of_memory

======================================================================
ERROR: test_interface.TestSolvers.test_solve_int64_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 72, in test_solve_int64_umfpack
    x = um.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 56, in spsolve
    x = UmfpackLU(A).solve(b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 192, in __init__
    self.umf = UmfpackContext(family[A.dtype.char + A.indices.dtype.char])
KeyError: 'dq'

======================================================================
ERROR: test_interface.TestSolvers.test_solve_sparse_rhs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 79, in test_solve_sparse_rhs
    x = um.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 56, in spsolve
    x = UmfpackLU(A).solve(b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 193, in __init__
    self.umf.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_invalid_matrix

======================================================================
ERROR: test_interface.TestSolvers.test_solve_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 63, in test_solve_umfpack
    x = um.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 56, in spsolve
    x = UmfpackLU(A).solve(b)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 193, in __init__
    self.umf.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_out_of_memory

======================================================================
ERROR: test_interface.TestSolvers.test_splu_solve
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 85, in test_splu_solve
    lu = um.splu(a)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 84, in splu
    return UmfpackLU(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 193, in __init__
    self.umf.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_out_of_memory

======================================================================
ERROR: test_interface.TestSolvers.test_splu_solve_int64
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 97, in test_splu_solve_int64
    lu = um.splu(a)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 84, in splu
    return UmfpackLU(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 192, in __init__
    self.umf = UmfpackContext(family[A.dtype.char + A.indices.dtype.char])
KeyError: 'dq'

======================================================================
ERROR: test_interface.TestSolvers.test_splu_solve_sparse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_interface.py", line 107, in test_splu_solve_sparse
    lu = um.splu(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 84, in splu
    return UmfpackLU(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\interface.py", line 193, in __init__
    self.umf.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_invalid_matrix

======================================================================
ERROR: test_umfpack.TestFactorization.test_complex_int64_lu
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 160, in test_complex_int64_lu
    umfpack.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 499, in symbolic
    indx = self._getIndx(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 478, in _getIndx
    raise ValueError('matrix must have long indices')
ValueError: matrix must have long indices

======================================================================
ERROR: test_umfpack.TestFactorization.test_real_int64_lu
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 201, in test_real_int64_lu
    umfpack.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 499, in symbolic
    indx = self._getIndx(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 478, in _getIndx
    raise ValueError('matrix must have long indices')
ValueError: matrix must have long indices

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_factorized_long_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 104, in test_factorized_long_umfpack
    solve = linsolve.factorized(a)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 376, in factorized
    umf = umfpack.UmfpackContext(_get_umf_family(A))
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 60, in _get_umf_family
    return family[dt]
KeyError: 'dq'

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_factorized_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 92, in test_factorized_umfpack
    solve = linsolve.factorized(a)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 379, in factorized
    umf.numeric(A)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_invalid_matrix

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_complex_long_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 60, in test_solve_complex_long_umfpack
    x = linsolve.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 143, in spsolve
    umf = umfpack.UmfpackContext(_get_umf_family(A))
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 60, in _get_umf_family
    return family[dt]
KeyError: 'Dq'

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_complex_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 51, in test_solve_complex_umfpack
    x = linsolve.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 145, in spsolve
    autoTranspose=True)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 753, in linsolve
    self.numeric(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_zl_symbolic at 0x00000244E656E0D0> failed with UMFPACK_ERROR_invalid_matrix

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_long_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 77, in test_solve_long_umfpack
    x = linsolve.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 143, in spsolve
    umf = umfpack.UmfpackContext(_get_umf_family(A))
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 60, in _get_umf_family
    return family[dt]
KeyError: 'dq'

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_sparse_rhs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 85, in test_solve_sparse_rhs
    x = linsolve.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 145, in spsolve
    autoTranspose=True)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 753, in linsolve
    self.numeric(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_invalid_matrix

======================================================================
ERROR: test_umfpack.TestScipySolvers.test_solve_umfpack
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python36\lib\site-packages\scikits\umfpack\tests\test_umfpack.py", line 68, in test_solve_umfpack
    x = linsolve.spsolve(a, b)
  File "X:\Python36\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 145, in spsolve
    autoTranspose=True)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 753, in linsolve
    self.numeric(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 539, in numeric
    self.symbolic(mtx)
  File "X:\Python36\lib\site-packages\scikits\umfpack\umfpack.py", line 520, in symbolic
    umfStatus[status]))
RuntimeError: <function umfpack_dl_symbolic at 0x00000244E656DF28> failed with UMFPACK_ERROR_invalid_matrix

----------------------------------------------------------------------
Ran 21 tests in 0.141s

FAILED (errors=17)
```

### PR DESCRIPTION
**Pull request by rc**
This version contains the following changes:

-   Merge pull request #47 from xoviat/manylinux
-   Merge pull request #44 from {rc,xoviat}/fix-win-amd64-dtypes, closes #36
-   Merge pull request #45 from xoviat/setup
-   Merge pull request #43 from xoviat/build-windows
-   Merge pull request #42 from xoviat/pytest
-   Merge pull request #39 from rc/replace-warning-manager
-   Merge pull request #38 from rgommers/build-requires

@rgommers, @xoviat - there is now an install dependence in `setup.py` for `scipy>=1.0.0rc1`. I would prefer to wait with the release until 'scipy-1.0.0' is out, so that `pip install --user scikit-umfpack` works.  What do you think? Great job, @xoviat, thanks for the windows problem solution and the manylinux wheels!

Also, maybe *README.rst*, *docs/release.rst* and *docs/install.rst* need updating (nose -> pytest, using `pip install` instead of `python setup.py install` - is this now preferred?).

### CODE REVIEW

**Comment by xoviat** [comment]
> What do you think? 

There's no reason to wait really because `pip install --pre --user scikit-umfpack` will work now and `pip install --user scikit-umfpack` will work immediately after scipy is released.

> using pip install instead of python setup.py install - is this now preferred

Yes. `python setup.py install` is in fact on track to be removed in future versions. It will be replaced with `python setup.py bdist_wheel` so that everything goes through the wheel route.

> nose -> pytest

Nose can actually still and is required to run the tests, but py.test is now an option. To switch over fully, you just need to remove `import nose`.

**Comment by rc** [comment]
OK, I will make the release now. Could you review this PR, please? I have updated the installation instructions.

**Comment by rgommers** [comment]
Waiting one week doesn't matter much though, so I think it's sensible to wait. Not being compatible with the last released version of one of your dependencies is not quite right.

**Comment by rc** [comment]
Oh, it is just one week already :) No problem with waiting.

**Comment by rgommers** [comment]
Yep, RC2 should be announced in an hour or so, and I don't expect any issues at this point anymore that require a third RC. So final release next week.

**Comment by rc** [comment]
Scipy 1.0.0 is out (@rgommers, congratulations!), so I will proceed. One question though: in the scikit-umfpack source directory:
```
pip install . --user
```
seems to always download and build scipy-1.0.0.tar.gz, even though it is already installed. Is this to be expected?

**Comment by xoviat** [comment]
Might update the req to scipy >= 1.0.

**Comment by rc** [comment]
I will rebase this PR's branch on master after #49 is merged. Could someone review?

**Comment by rgommers** [comment]
thanks:)

> seems to always download and build scipy-1.0.0.tar.gz, even though it is already installed. Is this to be expected?

there were a couple of wheels delayed due to TravisCI hiccups yesterday. should be fixed now. let me know if it's still a problem

**Comment by rc** [comment]
@rgommers It works fine now, thanks!

**Comment by rc** [comment]
OK, making the release today.

**Pull request merged**
