### PR TITLE
Version info

### PR DESCRIPTION
**Pull request by rc**
This PR addresses #7.

### CODE REVIEW

**Comment by xoviat** [comment]
If you're doing git versions, you should consider using setuptools_scm.

**Comment by rc** [comment]
Didn't know about that, thanks! But in this case, sticking to the simple solution that scipy uses seems easier for me (and no extra dependency).

**Comment by rc** [comment]
Or, does this approach pose problems on some platforms? If not, I propose merging this - it can be improved later. :)

**Comment by xoviat** [comment]
I can't personally speak to this approach. I personally would use `setuptools_scm` because it's less code to maintain, but it's your project, so it's up to you. As I won't be maintaining this, you should use the approach that you think is best.

**Comment by rc** [comment]
I played with `get_version()` of setuptools_scm a bit and it seems really nice, but I like the `version.py` as generated by scipy (and could not achieve that with setuptools_scm easily enough - maybe my bad). Anyway, thanks for your feedback! I will merge this for now, and rebase #48.

**Pull request merged**
