### PR TITLE
replace deprecated WarningManager by suppress_warnings()

### PR DESCRIPTION
**Pull request by rc**
See #38.

### CODE REVIEW

**Comment by rc** [comment]
@rgommers Could you review this PR? My plan, if it works, is to merge this PR and then rebase #37 on it.

**Comment by rgommers** [comment]
This change looks good, assuming you're happy to not support numpy < 1.12.0

The blanket filtering of deprecation warnings that was already there is fishy though, would be good to either make that more specific or (better) not to call deprecated code.

**Comment by rc** [comment]
Yeah, I am not sure why the deprecation warnings filter was there, I will try removing it. As for numpy < 1.12.0, as scipy supports 1.8.2 for Python 3.4, I would replace `suppress_warnings()` by `warnings.catch_warnings` - OK?

**Comment by rgommers** [comment]
Yes that sounds good

**Comment by rc** [comment]
Done (but I forgot to put `MAINT:` prefix to commit messages).

**Comment by rgommers** [comment]
LGTM, and no deprecation warnings are visible when testing again scipy 1.0.x

> but I forgot to put MAINT: prefix to commit messages).

that's just a numpy/scipy convention - I like it, but no need to follow it:)

**Comment by rc** [comment]
OK, so I guess I will merge it myself. Thanks!

**Pull request merged**
