### PR TITLE
Switch to Meson as build system, fix build issues, and add CI jobs

### PR DESCRIPTION
**Pull request by rgommers**
This was more complicated than expected, quite a few things needed fixing. But the end result should work with latest Python and NumPy, and also give cleaner build output.

I added two Linux CI jobs, for Ubuntu and Conda-forge. I haven't tested on macOS or Windows; dealing with finding the correct Suitesparse is a bit of a pain.

SWIG support is a little hacky, that should be improved (upstream issue for that is https://github.com/mesonbuild/meson/issues/341).

Note that the changes are large, so I changed the version number to `0.4.0.dev0`. That version number is found in two places; those need to be updated to `0.4.0` right before a release.

### CODE REVIEW

**Comment by rc** [comment]
Great, thank you for addressing this! Looking at the changes, that would take me ages to find out the correct incantations. :)

What is the correct way to develop locally now?

- I managed to run `meson setup` and `meson compile` successfully. How do I install the project?
- I can also run `pip install --upgrade --user .`, but then ` pytest scikits/umfpack` (in the git repo directory) fails.

After I resolve the above newbie issues, I will update `README.rst` and also the files in `docs/` to reflect the changes.

**Comment by rgommers** [comment]
> What is the correct way to develop locally now?

I'd suggest to keep it simple and use only editable installs and pytest:
```
pip install --no-build-isolation -e .
pytest
```
The one thing to understand is that `--no-build-isolation` is essential (see https://mesonbuild.com/meson-python/how-to-guides/editable-installs.html for why), and that it installs a `.pth` file into site-packages which automatically rebuilds by invoking `ninja`. Which is also handy, so no need to manually rerun the build when modifying `umfpack.i`. 

> I can also run `pip install --upgrade --user .`, but then ` pytest scikits/umfpack` (in the git repo directory) fails.

A regular `pip install .` works as expected (`--user` is harmless but obsolete) indeed. But to run pytest against an installed package, you need to do `cd docs && pytest --pyargs scikits.umfpack` like in the CI jobs. When you do `pytest scikits/umfpack` in the root of the repo, the import finds the uninstalled local source tree instead of the installed package.

**Comment by rc** [comment]
Thank you, it works like a charm!

More things I am not sure about:

- Previously we used `python setup.py build_ext -i build_sphinx` and `docs/do-gh-pages.sh` for working with the sphinx docs. Now I can run `make html` manually in `docs`, and update `docs/do-gh-pages.sh` too. Is that OK?

- https://scikit-umfpack.github.io/scikit-umfpack/install.html mentions `site.cfg` - that is now obsolete and can be removed, right?

- For PyPi uploads (see https://scikit-umfpack.github.io/scikit-umfpack/release.html also to be updated), former `python setup.py sdist` is now `meson dist -C build/cp310/`, where the last subdirectory name depends on the Python version. This produced `build/cp310/meson-dist/scikits.umfpack-0.4.0.dev0.tar.xz`, and I got
```
twine upload -r testpypi build/cp310/meson-dist/scikits.umfpack-0.4.0.dev0.tar.xz
Uploading distributions to https://test.pypi.org/legacy/
ERROR    InvalidDistribution: Unknown distribution format:                      
         'scikits.umfpack-0.4.0.dev0.tar.xz'                                    
```

-  Can I push into your branch?

**Comment by rc** [comment]
Then
```
meson dist -C build/cp310/ --allow-dirty --formats=gztar
twine upload -r testpypi build/cp310/meson-dist/scikits.umfpack-0.4.0.dev0.tar.gz
...
ValueError: No PKG-INFO in archive: ~/projects/scikit-umfpack/build/cp310/meson-dist/scikits.umfpack-0.4.0.dev0.tar.gz
```

**Comment by rgommers** [comment]
> Now I can run `make html` manually in `docs`, and update `docs/do-gh-pages.sh` too. Is that OK?

Yes, that sounds fine.

> mentions `site.cfg` - that is now obsolete and can be removed, right?

Ah yes, `site.cfg` was specific to `numpy.distutils` and can no longer be used. If there is a need for a replacement, there are a couple of ways:
- what already works is to craft ones own `UMFPACK.pc`, similar to http://scipy.github.io/devdocs/building/blas_lapack.html#using-pkg-config-to-detect-libraries-in-a-nonstandard-location
- It's also easy enough to add a custom CLI flag to the build; that goes in a `meson.options` file and is retrieved in `meson.build` with `get_option('opt_name')`. And then a user can pass it in on the command line with something like `pip install . -Csetup-args=-Dopt_name=opt_val`

> former `python setup.py sdist` is now `meson dist -C build/cp310/`, where the last subdirectory name depends on the Python version. This produced `build/cp310/meson-dist/scikits.umfpack-0.4.0.dev0.tar.xz`, and I got

That does not sounds right. The canonical way to build an sdist is to do in a clean repo:
```
python -m build --sdist
```
It should produce a `.tar.gz`, rather than `.xz`.

I'll also note that a plain `python -m build`, as done in CI, builds an sdist and then the wheel from the sdist, so that the sdist generation is actually tested in CI.

> Can I push into your branch?

Sure, no problem.

**Comment by rc** [comment]
> That does not sounds right. The canonical way to build an sdist is to do in a clean repo:
> 
> ```
> python -m build --sdist
> ```
> 
> It should produce a `.tar.gz`, rather than `.xz`.
> 
> I'll also note that a plain `python -m build`, as done in CI, builds an sdist and then the wheel from the sdist, so that the sdist generation is actually tested in CI.

Another new tool I was not aware of! Thanks!

**Comment by rc** [comment]
I went through all the docs and updated & tested all the given instructions. Also https://test.pypi.org/project/scikit-umfpack/0.4.0.dev0/ works for me, so I guess we are ready to merge.

**Comment by rgommers** [comment]
Great! Your updates LGTM

**Pull request merged**
