### PR TITLE
Use travis-CI

### PR DESCRIPTION
**Pull request by pv**
Enable Travis-CI.

@rc: you need to turn Travis on (need to have admin permissions to do this) --- log in to https://travis-ci.org go to your account page, and turn it on for this repository.

### CODE REVIEW

**Comment by rc** [comment]
I guess it is enabled. So now I merge this PR?

**Comment by pv** [comment]
Let's merge it after it works --- may need still some tuning

**Comment by rc** [comment]
OK, waiting :)

**Comment by pv** [comment]
Should be fine now, please merge.

**Comment by rc** [comment]
Thank you, it is merged.

**Pull request merged**
